spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlserver://DESKTOP-8MC2SNF\\MSSQLSERVER01:1433;databaseName=Test;encrypt=false;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL}"
    password: "${MAILPASS}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: "/api/v1"

jwt:
  signerKey: "${SIGNER_KEY}"
  refreshSignerKey: "${REFRESH_SIGNER_KEY}"
  validTime: 300 #second
  refreshTime: 2628000 #second (1 month)

frontend:
  url: "${FRONTEND_URL}"

