spring:
  application:
    name: backend

  datasource:
    url: jdbc:sqlserver://${DATABASE_URL};databaseName=${DATABASE_NAME};trustServerCertificate=true;encrypt=false;characterEncoding=UTF-8;
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL}"
    password: "${MAILPASS}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "dev.chinhcd.backend.dtos.request.classDTO"
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "all"
      retries: 1
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

server:
  port: 8080
  servlet:
    context-path: "/api/v1"

jwt:
  signerKey: "${SIGNER_KEY}"
  refreshSignerKey: "${REFRESH_SIGNER_KEY}"
  validTime: 300 #second
  refreshTime: 2628000 #second (1 month)

frontend:
  url: "${FRONTEND_URL}"

